---
- name: os patching
  hosts: all
  become: yes

  tasks:
    - name: List listening ports and save to file
      command: netstat -lutnp
      register: port_output

    - name: Save listening ports to file
      copy:
        content: "{{ port_output.stdout }}"
        dest: /tmp/listening_ports.txt
        owner: root
        group: root
        mode: '0644'
    
    - name: server utilization
      command: top
      register: top_output

    - name: save top to file 
      copy:
        content: "{{ top_output.stdout }}"
        dest: /tmp/uptime.txt
        owner: root
        group: root
        mode: '0644'

    - name: kernal version
      command: cat /etc/*se
      register: kernal_output

    - name: save kernal version to file 
      copy:
        content: "{{ kernal_output.stdout }}"
        dest: /tmp/keranl.txt 
        owner: root
        group: root
        mode: "0644"

    - name: latest updates 
      yum:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
    - name: install httpd
      yum:
          name: httpd
          state: present

    - name: service restart
      service:
        name: httpd
        state: restarted
        enabled: yes