---
- name: os patching
  hosts: all
  become: yes

  tasks:
- name: istalling latest updates 
  yum:
    name: update
    state: latest

- name: install httpd
  dnf:
    name: httpd
    state: present

- name: service restart
  service:
    name: httpd
    state: restarted
    enabled: yes