---
- name: Prechecks for patching
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: uptime
    command: uptime
    register: uptime_before

  - name: get kernel version from node servers
    command: uname -r
    register: skernal_before

  - name: listening ports
    command: netstat -lutnp # ss -lutnp
    register: port_output

  - name: listening port
    copy: 
      contest: "{{port_output.stdout}}"
      dest: /tmp/neeladri.txt
      owner: root
      group: root
      mode: "0644"